version: '3.4'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    hostname: ${MYSQL_HOST:?mysql host not set}
    networks:
      - test_net
    volumes:
      - gomvc-test-storage:/var/lib/mysql
    ports:
      - 3306:${MYSQL_PORT:?mysql port not set}
    
  http_server:
    image: gomvc:latest
    depends_on:
      - mysql_db
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: http_server
    hostname: http-server
    networks:
      - test_net
    ports:
      - 8080:8080
    deploy:
      restart_policy: 
        condition: on-failure
    environment:
      - MYSQL_HOST=${MYSQL_HOST:?mysql host not set}
      - MYSQL_PORT=${MYSQL_PORT:?mysql host not set}

volumes:
  gomvc-test-storage:

networks:
  test_net:
    driver: bridge
