version: '3.4'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    hostname: db
    networks:
      - test_net
    volumes:
      - gomvc-test-storage:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  http_server:
    image: gomvc:latest
    depends_on:
      - mysql_db
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: http_server
    hostname: http-server
    networks:
      - test_net
    ports:
      - 8080:8080
    deploy:
      restart_policy: 
        condition: on-failure

volumes:
  gomvc-test-storage: # TODO fix directory issue

networks:
  test_net: # TODO check the network name and fix it
    driver: bridge
